# Site settings
title: India Latin America Associates
email: pk.kapur@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  India Latin America Associates promotes cross-cultural, commercial, and
  economic development of the two regions.
baseurl: /LATAM
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from

gallerytag:
    dir: img/gallery
    url: /photos
    thumb_width: 150
    thumb_height: 150
    columns: 4